version: "2.1"

networks:
  oracle:
    name: oracle
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.10.10.0/24

services:
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=33679
      - PGID=33679
      - TZ=Europe/Kiev
      - AUTO_UPDATE=true
    volumes:
      - /data/jackett/config:/config
    ports:
      - 9117:9117
    restart: unless-stopped
    networks:
      oracle:
        ipv4_address: 10.10.10.10

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=33679
      - PGID=33679
      - TZ=Europe/Kiev
    volumes:
      - /data/sonarr/config:/config
      - /usb1:/usb1
    ports:
      - 8989:8989
    restart: no
    networks:
      oracle:

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=33679
      - PGID=33679
      - TZ=Europe/Kiev
    volumes:
      - /data/radarr/config:/config
      - /usb1:/usb1
    ports:
      - 7878:7878
    restart: no
    networks:
      oracle:

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      oracle:

  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=33679
      - PGID=33679
      - TZ=Europe/Kiev
    volumes:
      - /data/duplicati/config:/config
      - /data:/source
    ports:
      - 8200:8200
    restart: unless-stopped
    networks:
      oracle:

  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=33679
      - PGID=33679
      - TZ=Europe/Kiev
    volumes:
      - /data/heimdall/config:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    networks:
      oracle:
