version: "2.1"

services:
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=33679
      - PGID=33679
      - TZ=Europe/Kiev
      - AUTO_UPDATE=true
    volumes:
      - /data/jackett/config:/config
    ports:
      - 9117:9117
    restart: always
    networks:
      bridge:
        ipv4_address: 172.17.0.10

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=33679
      - PGID=33679
      - TZ=Europe/Kiev
    volumes:
      - /data/sonarr/config:/config
      - /usb1:/usb1
    ports:
      - 8989:8989
    restart: no

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=33679
      - PGID=33679
      - TZ=Europe/Kiev
    volumes:
      - /data/radarr/config:/config
      - /usb1:/usb1
    ports:
      - 7878:7878
    restart: no